 Verzeichnis von C:\Users\PP021887\python-pakete

08.05.2025  20:41    <DIR>          .
08.05.2025  19:05    <DIR>          ..
08.05.2025  18:36           159.618 certifi-2025.4.26-py3-none-any.whl
08.05.2025  20:38            39.748 charset_normalizer-2.1.1-py3-none-any.whl
08.05.2025  18:54            70.442 idna-3.10-py3-none-any.whl
08.05.2025  18:54           115.358 msal-1.32.3-py3-none-any.whl
08.05.2025  18:33         1.285.805 Office365_REST_Python_Client-2.6.1-py3-none-any.whl
08.05.2025  18:55           118.697 pycparser-2.21-py2.py3-none-any.whl
08.05.2025  18:36            22.591 PyJWT-2.8.0-py3-none-any.whl
08.05.2025  18:55            62.574 requests-2.31.0-py3-none-any.whl
08.05.2025  18:48            11.050 six-1.17.0-py2.py3-none-any.whl
08.05.2025  18:48            33.232 typing_extensions-4.7.1-py3-none-any.whl
08.05.2025  18:47           124.213 urllib3-2.0.7-py3-none-any.whll
              10 Datei(en),      2.003.580 Bytes
               2 Verzeichnis(se), 141.353.185.280 Bytes frei

âœ… So findest du alle installierten Python-Bibliotheken heraus
ðŸ”¹ CMD-Methode (am einfachsten)
Ã–ffne deine Eingabeaufforderung (CMD) und gib ein:

cmd
Kopieren
Bearbeiten
python -m pip list
Oder, falls du Python Ã¼ber einen direkten Pfad startest:

cmd
Kopieren
Bearbeiten
"C:\Program Files (x86)\Python37-32\python.exe" -m pip list
ðŸ“‹ Das zeigt dir alle installierten Pakete inkl. Versionen â€“ z.â€¯B.:

python-repl
Kopieren
Bearbeiten
Package                    Version
-------------------------- -------
pandas                     1.3.5
Office365-REST-Python-Client 2.6.1
requests                   2.31.0
...
ðŸ”¹ Alternative: Ausgabe in Datei speichern (fÃ¼r spÃ¤tere Dokumentation)
cmd
Kopieren
Bearbeiten
python -m pip list > installed_packages.txt
Damit wird die Liste als Textdatei gespeichert (z.â€¯B. im gleichen Ordner wie dein Skript), die du z.â€¯B. an mich weitergeben oder in eine Dokumentation Ã¼bernehmen kannst.

============================================================================================================================================
C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user certifi-2025.4.26-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\certifi-2025.4.26-py3-none-any.whl
Installing collected packages: certifi
Successfully installed certifi-2025.4.26

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user idna-3.10-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\idna-3.10-py3-none-any.whl
Installing collected packages: idna
Successfully installed idna-3.10

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user msal-1.32.3-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\msal-1.32.3-py3-none-any.whl
Collecting requests<3,>=2.0.0 (from msal==1.32.3)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F7B1D0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F7B510>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F7B5F0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F7B6D0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03F7B7B0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/requests/
  Could not find a version that satisfies the requirement requests<3,>=2.0.0 (from msal==1.32.3) (from versions: )
No matching distribution found for requests<3,>=2.0.0 (from msal==1.32.3)

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user requests-2.31.0-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\requests-2.31.0-py3-none-any.whl
Collecting charset-normalizer<4,>=2 (from requests==2.31.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2590>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/charset-normalizer/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2410>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/charset-normalizer/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2910>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/charset-normalizer/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF29F0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/charset-normalizer/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2AD0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/charset-normalizer/
  Could not find a version that satisfies the requirement charset-normalizer<4,>=2 (from requests==2.31.0) (from versions: )
No matching distribution found for charset-normalizer<4,>=2 (from requests==2.31.0)

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user charset_normalizer-2.1.1-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\charset_normalizer-2.1.1-py3-none-any.whl
Installing collected packages: charset-normalizer
  The script normalizer.exe is installed in 'C:\Users\PP021887\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed charset-normalizer-2.1.1

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user requests-2.31.0-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\requests-2.31.0-py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pp021887\appdata\roaming\python\python37\site-packages (from requests==2.31.0) (2025.4.26)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pp021887\appdata\roaming\python\python37\site-packages (from requests==2.31.0) (2.1.1)
Collecting urllib3<3,>=1.21.1 (from requests==2.31.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03C85E50>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/urllib3/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03CB2310>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/urllib3/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03CB23F0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/urllib3/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03CB24D0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/urllib3/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x03CB25B0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/urllib3/
  Could not find a version that satisfies the requirement urllib3<3,>=1.21.1 (from requests==2.31.0) (from versions: )
No matching distribution found for urllib3<3,>=1.21.1 (from requests==2.31.0)

C:\Users\PP021887\python-pakete>"C:\Program Files (x86)\Python37-32\python.exe" -m pip install --user Office365_REST_Python_Client-2.6.1-py3-none-any.whl
Processing c:\users\pp021887\python-pakete\office365_rest_python_client-2.6.1-py3-none-any.whl
Collecting typing-extensions>=4.0.0 (from Office365-REST-Python-Client==2.6.1)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04489770>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/typing-extensions/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04489AB0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/typing-extensions/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04489B90>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/typing-extensions/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04489C70>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/typing-extensions/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x04489D50>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/typing-extensions/
  Could not find a version that satisfies the requirement typing-extensions>=4.0.0 (from Office365-REST-Python-Client==2.6.1) (from versions: )
No matching distribution found for typing-extensions>=4.0.0 (from Office365-REST-Python-Client==2.6.1)

C:\Users\PP021887\python-pakete>python -m pip list
Package            Version
------------------ ---------
certifi            2025.4.26
charset-normalizer 2.1.1
idna               3.10
pip                19.0.3
setuptools         40.8.0
typing-extensions  4.7.1
urllib3            2.0.7
